[data]
name = "ScanNet"
n_class = 20
class_names = "mIoU,wall,floor,cabinet,bed,chair,sofa,table,door,window,bookshelf,picture,counter,desk,curtain,refridgerator,shower curtain,toilet,sink,bathtub,otherfurniture"
preprocess = "centered"

[model]
input_features = 'xyzrgb'
k_eig = 128
n_diffnet_blocks = 4
n_mlp_hidden = 2
dropout = true
gradient_rotation = false
c0 = 128

[model.hierarchy]
hierarchy = false
n_levels = 4
c1 = 32
c2 = 64
c3 = 96
c_m = 128

[training]
n_epoch = 200
pseudo_batch_size = 8
learning_rate = 1e-3
weight_decay = 0
lr_scheduler = 'step'
lr_step_size = 1
lr_step_gamma = 0.98
checkpt_every = 10

[training.augment]
rotate = true
translate = true
flip = true
scale = false
rgb_jitter = true
operators = true
translate_scale = 0.2
scaling_range = 0.5

[experiment]
name = ""
