[data]
name = "ScanNet"
n_class = 20
class_names = "mIoU,wall,floor,cabinet,bed,chair,sofa,table,door,window,bookshelf,picture,counter,desk,curtain,refridgerator,shower curtain,toilet,sink,bathtub,otherfurniture"
preprocess = "centered"

[model]
input_features = 'xyzrgb'
n_levels = 4
k_eig = 128
n_diffnet_blocks = 2
n_mlp_hidden = 2
dropout = true
c0 = 32
c1 = 32
c2 = 64
c3 = 96
c_m = 128

[training]
n_epoch = 200
pseudo_batch_size = 8
lr = 1e-3
lr_scheduler = 'step'
lr_step_size = 1
lr_step_gamma = 0.98
checkpt_every = 10

[training.augment]
rotate = true
other = true
translate_scale = 0.2
scaling_range = 0.5

[experiment]
name = ""
